/**
 * CRADI — Alert Distribution Cloud Function (Firebase Admin SDK)
 *
 * Trigger: Firestore onDocumentUpdated('reports/{reportId}')
 *          fires when a report's status transitions to 'validated'.
 *
 * Behaviour:
 *   1. Reads matching authority records from the 'authorities' Firestore collection.
 *   2. Sends an alert email to each authority in the same LGA/state via Resend.
 *
 * Env vars (set in Firebase console or .env):
 *   RESEND_API_KEY  — Resend API key (required)
 *   FROM_EMAIL      — sender address   (default: noreply@cradi.ng)
 *   FROM_NAME       — sender display name (default: EWER Alert System)
 */

'use strict';

const { onDocumentUpdated } = require('firebase-functions/v2/firestore');
const { initializeApp, getApps } = require('firebase-admin/app');
const { getFirestore } = require('firebase-admin/firestore');

if (!getApps().length) initializeApp();
const db = getFirestore();

// ─────────────────────────────────────────────────────────────────────────────
// Helper: normalise a string for fuzzy LGA/state matching
// ─────────────────────────────────────────────────────────────────────────────
function normalize(s) {
    return (s || '').toString().toLowerCase().replace(/[^a-z0-9]/g, '');
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: send email via Resend
// ─────────────────────────────────────────────────────────────────────────────
async function sendResendEmail({ to, subject, html, fromName, fromEmail }) {
    const apiKey = process.env.RESEND_API_KEY;
    if (!apiKey) throw new Error('RESEND_API_KEY not configured');

    const response = await fetch('https://api.resend.com/emails', {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${apiKey}`,
        },
        body: JSON.stringify({
            from: `${fromName} <${fromEmail}>`,
            to: Array.isArray(to) ? to : [to],
            subject,
            html,
        }),
    });

    if (!response.ok) {
        const text = await response.text();
        throw new Error(`Resend API ${response.status}: ${text}`);
    }
    return (await response.json()).id;
}

// ─────────────────────────────────────────────────────────────────────────────
// Helper: build alert email HTML
// ─────────────────────────────────────────────────────────────────────────────
function buildAlertHtml(report) {
    return `
<div style="font-family:sans-serif;max-width:600px;margin:0 auto;">
  <h2 style="color:#c0392b;">🚨 CRADI Disaster Alert</h2>
  <table style="border-collapse:collapse;width:100%;">
    <tr><td style="padding:6px;font-weight:bold;">Severity</td>
        <td style="padding:6px;">${report.severity || 'HIGH'}</td></tr>
    <tr><td style="padding:6px;font-weight:bold;">Hazard Type</td>
        <td style="padding:6px;">${report.hazardType || '—'}</td></tr>
    <tr><td style="padding:6px;font-weight:bold;">Ward</td>
        <td style="padding:6px;">${report.ward || '—'}</td></tr>
    <tr><td style="padding:6px;font-weight:bold;">LGA</td>
        <td style="padding:6px;">${report.lga || '—'}</td></tr>
    <tr><td style="padding:6px;font-weight:bold;">State</td>
        <td style="padding:6px;">${report.state || '—'}</td></tr>
  </table>
  <p style="margin-top:16px;">${report.description || 'No additional details provided.'}</p>
  <hr/>
  <p style="font-size:12px;color:#888;">
    This alert was automatically generated by the EWER monitoring system.
    Do not reply to this email.
  </p>
</div>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Cloud Function: distributeAlertEmail
// ─────────────────────────────────────────────────────────────────────────────
exports.distributeAlertEmail = onDocumentUpdated(
    { document: 'reports/{reportId}', region: 'us-central1' },
    async (event) => {
        const before = event.data.before.data();
        const after = event.data.after.data();

        // Only fire when status flips to 'validated'
        if (before.status === 'validated' || after.status !== 'validated') {
            return;
        }

        const { reportId } = event.params;
        console.log(`[distributeAlertEmail] Processing validated report: ${reportId}`);

        const targetState = normalize(after.state);
        const targetLga = normalize(after.lga);

        // ── Fetch authorities from Firestore ──────────────────────────────────
        const authSnap = await db.collection('authorities').limit(2000).get();
        const authorityEmails = authSnap.docs
            .filter(doc => {
                const d = doc.data();
                return normalize(d.state) === targetState && normalize(d.lga) === targetLga;
            })
            .map(doc => doc.data().email)
            .filter(Boolean);

        console.log(`[distributeAlertEmail] ${authorityEmails.length} authority email(s) found for ${after.lga}, ${after.state}`);

        if (authorityEmails.length === 0) {
            console.log('[distributeAlertEmail] No authority emails — skipping.');
            return;
        }

        // ── Send emails ───────────────────────────────────────────────────────
        const FROM_EMAIL = process.env.FROM_EMAIL || 'noreply@cradi.ng';
        const FROM_NAME = process.env.FROM_NAME || 'EWER Alert System';
        const subject = `[CRADI ALERT] ${(after.severity || 'HIGH').toUpperCase()} ${after.hazardType} — ${after.lga}`;
        const html = buildAlertHtml(after);

        let emailsSent = 0;
        let emailsFailed = 0;

        await Promise.all(
            authorityEmails.map(async (email) => {
                try {
                    await sendResendEmail({ to: email, subject, html, fromName: FROM_NAME, fromEmail: FROM_EMAIL });
                    emailsSent++;
                    console.log(`[distributeAlertEmail] ✅ Sent to ${email}`);
                } catch (err) {
                    emailsFailed++;
                    console.error(`[distributeAlertEmail] ❌ Failed for ${email}: ${err.message}`);
                }
            }),
        );

        console.log(
            `[distributeAlertEmail] Done — sent: ${emailsSent}, failed: ${emailsFailed}`,
        );
    },
);
