/**
 * Stands up a project and an API key on the local Appwrite.
 *
 *   node infra/appwrite/local/bootstrap.mjs
 *
 * Writes `infra/appwrite/local/.env.local` (gitignored) with the project
 * id and key, so `provision.mjs` and the tests can source it.
 *
 * Adapted from the Phase 0 spike's `setup.mjs`. The scopes are wider —
 * these have to cover buckets, functions and messaging, which the spike
 * did not need.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const EP = process.env.LOCAL_ENDPOINT ?? 'http://localhost:8090/v1';
const here = dirname(fileURLToPath(import.meta.url));
const jar = {};

async function call(path, { method = 'GET', body, project = 'console', key } = {}) {
  const headers = { 'content-type': 'application/json', 'x-appwrite-project': project };
  if (key) headers['x-appwrite-key'] = key;
  if (jar.cookie) headers.cookie = jar.cookie;
  const res = await fetch(`${EP}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  const setCookie = res.headers.get('set-cookie');
  if (setCookie) jar.cookie = setCookie.split(';')[0];
  const text = await res.text();
  let parsed;
  try { parsed = JSON.parse(text); } catch { parsed = text; }
  return { ok: res.ok, status: res.status, body: parsed };
}

const email = 'root@cradi.test';
const password = 'LocalRootPassword123';

const account = await call('/account', {
  method: 'POST',
  body: { userId: 'unique()', email, password, name: 'Local Root' },
});
console.log(account.ok ? 'root account created' : `root account: ${account.status}`);

const session = await call('/account/sessions/email', {
  method: 'POST',
  body: { email, password },
});
if (!session.ok) throw new Error(`sign-in failed: ${JSON.stringify(session.body).slice(0, 200)}`);
console.log('signed in');

const team = await call('/teams', {
  method: 'POST',
  body: { teamId: 'unique()', name: 'CRADI' },
});
if (!team.ok) throw new Error(`team failed: ${JSON.stringify(team.body).slice(0, 200)}`);

const project = await call('/projects', {
  method: 'POST',
  body: { projectId: 'cradi', name: 'CRADI', teamId: team.body.$id, region: 'default' },
});
const projectId = project.ok ? project.body.$id : 'cradi';
console.log(`project: ${projectId}${project.ok ? '' : ' (existing)'}`);

const key = await call(`/projects/${projectId}/keys`, {
  method: 'POST',
  body: {
    name: 'provisioner',
    scopes: [
      'users.read', 'users.write',
      'teams.read', 'teams.write',
      'databases.read', 'databases.write',
      'collections.read', 'collections.write',
      'attributes.read', 'attributes.write',
      'indexes.read', 'indexes.write',
      'documents.read', 'documents.write',
      'buckets.read', 'buckets.write',
      'files.read', 'files.write',
      'functions.read', 'functions.write',
      'execution.read', 'execution.write',
      'targets.read', 'targets.write',
      'providers.read', 'providers.write',
      'messages.read', 'messages.write',
      'topics.read', 'topics.write',
      'subscribers.read', 'subscribers.write',
      'sessions.write',
    ],
  },
});
if (!key.ok) throw new Error(`key failed: ${JSON.stringify(key.body).slice(0, 300)}`);

const envPath = resolve(here, '.env.local');
writeFileSync(
  envPath,
  `# Local Appwrite only. Generated by bootstrap.mjs; gitignored.\n` +
    `export APPWRITE_ENDPOINT='${EP}'\n` +
    `export APPWRITE_PROJECT_ID='${projectId}'\n` +
    `export APPWRITE_API_KEY='${key.body.secret}'\n` +
    `export APPWRITE_DATABASE_ID='cradi'\n`,
);
console.log(`wrote ${envPath}`);
console.log('\nsource infra/appwrite/local/.env.local');
