// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1UtBDV_bO2Qbyz3vOihDCs747lM3ASCM',
    appId: '1:689251502200:android:3c102d339da6c4437e458d',
    messagingSenderId: '689251502200',
    projectId: 'ewer-8f788',
    storageBucket: 'ewer-8f788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOcfV0I36c1d3E7SEzWWHV5ewlXFViJWM',
    appId: '1:689251502200:ios:844c6e09186ae4e47e458d',
    messagingSenderId: '689251502200',
    projectId: 'ewer-8f788',
    storageBucket: 'ewer-8f788.firebasestorage.app',
    iosBundleId: 'com.westgatestratagem.climateapp.climateApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLBBkjPb8zMACJWHpzKTiUpGjnaJMnZ4k',
    appId: '1:689251502200:web:1697afa7d602215e7e458d',
    messagingSenderId: '689251502200',
    projectId: 'ewer-8f788',
    authDomain: 'ewer-8f788.firebaseapp.com',
    storageBucket: 'ewer-8f788.firebasestorage.app',
    measurementId: 'G-Q4JXEN9J5M',
  );
}
