// Mocks generated by Mockito 5.4.6 from annotations
// in climate_app/test/widget/hazard_selection_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i6;

import 'package:climate_app/features/reporting/providers/reporting_provider.dart'
    as _i2;
import 'package:flutter/material.dart' as _i5;
import 'package:image_picker/image_picker.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDateTime_0 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReportingProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportingProvider extends _i1.Mock implements _i2.ReportingProvider {
  MockReportingProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  DateTime get reportDateTime =>
      (super.noSuchMethod(
            Invocation.getter(#reportDateTime),
            returnValue: _FakeDateTime_0(
              this,
              Invocation.getter(#reportDateTime),
            ),
          )
          as DateTime);

  @override
  List<_i3.XFile> get photos =>
      (super.noSuchMethod(
            Invocation.getter(#photos),
            returnValue: <_i3.XFile>[],
          )
          as List<_i3.XFile>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setHazardType(String? type) => super.noSuchMethod(
    Invocation.method(#setHazardType, [type]),
    returnValueForMissingStub: null,
  );

  @override
  void setSeverity(String? level) => super.noSuchMethod(
    Invocation.method(#setSeverity, [level]),
    returnValueForMissingStub: null,
  );

  @override
  void setLocationDetails(String? details) => super.noSuchMethod(
    Invocation.method(#setLocationDetails, [details]),
    returnValueForMissingStub: null,
  );

  @override
  void setLocation(double? lat, double? lng) => super.noSuchMethod(
    Invocation.method(#setLocation, [lat, lng]),
    returnValueForMissingStub: null,
  );

  @override
  void setDescription(String? desc) => super.noSuchMethod(
    Invocation.method(#setDescription, [desc]),
    returnValueForMissingStub: null,
  );

  @override
  void setReportDateTime(DateTime? dateTime) => super.noSuchMethod(
    Invocation.method(#setReportDateTime, [dateTime]),
    returnValueForMissingStub: null,
  );

  @override
  void setWard(String? ward) => super.noSuchMethod(
    Invocation.method(#setWard, [ward]),
    returnValueForMissingStub: null,
  );

  @override
  void setLGA(String? lga) => super.noSuchMethod(
    Invocation.method(#setLGA, [lga]),
    returnValueForMissingStub: null,
  );

  @override
  void setReportState(String? state) => super.noSuchMethod(
    Invocation.method(#setReportState, [state]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> pickImage(_i3.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [source]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void removeImage(int? index) => super.noSuchMethod(
    Invocation.method(#removeImage, [index]),
    returnValueForMissingStub: null,
  );

  @override
  void reset() => super.noSuchMethod(
    Invocation.method(#reset, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<Map<String, dynamic>> submitReport(_i5.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#submitReport, [context]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> syncPendingReports(
    _i5.BuildContext? context,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingReports, [context]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
