// Mocks generated by Mockito 5.4.6 from annotations
// in climate_app/test/widget/knowledge_detail_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i4;

import 'package:climate_app/features/knowledge_base/providers/knowledge_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [KnowledgeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockKnowledgeProvider extends _i1.Mock implements _i2.KnowledgeProvider {
  MockKnowledgeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<Map<String, dynamic>> get guides =>
      (super.noSuchMethod(
            Invocation.getter(#guides),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  List<Map<String, dynamic>> guidesFor(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#guidesFor, [category]),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  bool isLoadingCategory(String? category) =>
      (super.noSuchMethod(
            Invocation.method(#isLoadingCategory, [category]),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> fetchGuides({String? category}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchGuides, [], {#category: category}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<Map<String, dynamic>> searchGuides(String? query, {String? category}) =>
      (super.noSuchMethod(
            Invocation.method(#searchGuides, [query], {#category: category}),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
