// Mocks generated by Mockito 5.4.6 from annotations
// in climate_app/test/widget/reports_status_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i7;

import 'package:climate_app/features/auth/providers/auth_provider.dart' as _i8;
import 'package:climate_app/features/profile/providers/profile_provider.dart'
    as _i3;
import 'package:climate_app/features/verification/models/verification_report_model.dart'
    as _i4;
import 'package:climate_app/features/verification/providers/reports_status_provider.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ReportsStatusProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockReportsStatusProvider extends _i1.Mock
    implements _i2.ReportsStatusProvider {
  MockReportsStatusProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSubmitting =>
      (super.noSuchMethod(Invocation.getter(#isSubmitting), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateContext(_i3.ProfileProvider? profileProvider) =>
      super.noSuchMethod(
        Invocation.method(#updateContext, [profileProvider]),
        returnValueForMissingStub: null,
      );

  @override
  List<_i4.VerificationReport> getReports(
    _i4.ReportStatus? status, {
    String? userId,
    String? excludeUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getReports,
              [status],
              {#userId: userId, #excludeUserId: excludeUserId},
            ),
            returnValue: <_i4.VerificationReport>[],
          )
          as List<_i4.VerificationReport>);

  @override
  bool hasMore(
    _i4.ReportStatus? status, {
    String? userId,
    String? excludeUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #hasMore,
              [status],
              {#userId: userId, #excludeUserId: excludeUserId},
            ),
            returnValue: false,
          )
          as bool);

  @override
  bool isLoading(
    _i4.ReportStatus? status, {
    String? userId,
    String? excludeUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #isLoading,
              [status],
              {#userId: userId, #excludeUserId: excludeUserId},
            ),
            returnValue: false,
          )
          as bool);

  @override
  int getTotal(
    _i4.ReportStatus? status, {
    String? userId,
    String? excludeUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getTotal,
              [status],
              {#userId: userId, #excludeUserId: excludeUserId},
            ),
            returnValue: 0,
          )
          as int);

  @override
  _i5.Future<void> submitVerificationRequest({
    required String? hazardType,
    required String? severity,
    required String? description,
    required String? userId,
    required String? state,
    required String? lga,
    required String? ward,
    String? locationDetails,
    double? latitude,
    double? longitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#submitVerificationRequest, [], {
              #hazardType: hazardType,
              #severity: severity,
              #description: description,
              #userId: userId,
              #state: state,
              #lga: lga,
              #ward: ward,
              #locationDetails: locationDetails,
              #latitude: latitude,
              #longitude: longitude,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> refreshReports({String? excludeUserId, String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#refreshReports, [], {
              #excludeUserId: excludeUserId,
              #userId: userId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> fetchReports({
    bool? loadMore = false,
    _i4.ReportStatus? status,
    String? userId,
    String? excludeUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchReports, [], {
              #loadMore: loadMore,
              #status: status,
              #userId: userId,
              #excludeUserId: excludeUserId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.VerificationReport>> getAllReports() =>
      (super.noSuchMethod(
            Invocation.method(#getAllReports, []),
            returnValue: _i5.Future<List<_i4.VerificationReport>>.value(
              <_i4.VerificationReport>[],
            ),
          )
          as _i5.Future<List<_i4.VerificationReport>>);

  @override
  _i5.Future<void> verifyReport(String? reportId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#verifyReport, [reportId], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> approveReport(String? reportId) =>
      (super.noSuchMethod(
            Invocation.method(#approveReport, [reportId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> rejectReport(String? reportId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#rejectReport, [reportId], {#userId: userId}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> moveBackToPending(String? reportId) =>
      (super.noSuchMethod(
            Invocation.method(#moveBackToPending, [reportId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> generateCSVReport(_i4.ReportStatus? filterStatus) =>
      (super.noSuchMethod(
            Invocation.method(#generateCSVReport, [filterStatus]),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#generateCSVReport, [filterStatus]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isVerified =>
      (super.noSuchMethod(Invocation.getter(#isVerified), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasCompletedOnboarding =>
      (super.noSuchMethod(
            Invocation.getter(#hasCompletedOnboarding),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLocked =>
      (super.noSuchMethod(Invocation.getter(#isLocked), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  bool canVoteOn({String? reporterId, String? reportWard}) =>
      (super.noSuchMethod(
            Invocation.method(#canVoteOn, [], {
              #reporterId: reporterId,
              #reportWard: reportWard,
            }),
            returnValue: false,
          )
          as bool);

  @override
  bool canManageReportStatus({String? reporterId}) =>
      (super.noSuchMethod(
            Invocation.method(#canManageReportStatus, [], {
              #reporterId: reporterId,
            }),
            returnValue: false,
          )
          as bool);

  @override
  _i5.Future<void> reloadUserData() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUserData, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> completeOnboarding() =>
      (super.noSuchMethod(
            Invocation.method(#completeOnboarding, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> unlockApp() =>
      (super.noSuchMethod(
            Invocation.method(#unlockApp, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signUpWithEmail({
    required String? email,
    required String? password,
    String? name,
    String? address,
    _i8.UserRole? role,
    String? state,
    String? lga,
    String? ward,
    String? phoneNumber,
    String? ndpaPolicyVersion,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUpWithEmail, [], {
              #email: email,
              #password: password,
              #name: name,
              #address: address,
              #role: role,
              #state: state,
              #lga: lga,
              #ward: ward,
              #phoneNumber: phoneNumber,
              #ndpaPolicyVersion: ndpaPolicyVersion,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> signInWithEmail({
    required String? email,
    required String? password,
    bool? rememberMe = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [], {
              #email: email,
              #password: password,
              #rememberMe: rememberMe,
            }),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendOtpForPhone(
    String? phone, {
    Map<String, dynamic>? registrationData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendOtpForPhone,
              [phone],
              {#registrationData: registrationData},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> sendOtpForEmail(String? email, {String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#sendOtpForEmail, [email], {#name: name}),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> verifyOtpAndLogin(
    String? otp, {
    Map<String, dynamic>? registrationData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #verifyOtpAndLogin,
              [otp],
              {#registrationData: registrationData},
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> resendVerificationLink() =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationLink, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> confirmPasswordReset({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#confirmPasswordReset, [], {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> authenticateWithBiometrics() =>
      (super.noSuchMethod(
            Invocation.method(#authenticateWithBiometrics, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> setBiometricEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setBiometricEnabled, [enabled]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isBiometricEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isBiometricAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isBiometricAvailable, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void recordActivity() => super.noSuchMethod(
    Invocation.method(#recordActivity, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<bool> validateSession() =>
      (super.noSuchMethod(
            Invocation.method(#validateSession, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Duration?> getSessionTimeRemaining() =>
      (super.noSuchMethod(
            Invocation.method(#getSessionTimeRemaining, []),
            returnValue: _i5.Future<Duration?>.value(),
          )
          as _i5.Future<Duration?>);

  @override
  _i5.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
