/// Application-level configuration constants.
///
/// All Appwrite constants (endpoint, projectId, databaseId, storageBucketId)
/// have been removed as part of the Appwrite → Firebase migration.
/// Firebase is configured via `firebase_options.dart` (generated by FlutterFire CLI).
class AppConfig {
  AppConfig._();

  // ── Firebase project ────────────────────────────────────────────────────────
  static const String firebaseProjectId = 'ewer-8f788';

  // ── Firestore collection names ──────────────────────────────────────────────
  static const String usersCollection = 'users';
  static const String reportsCollection = 'reports';
  static const String chatsCollection = 'chats';
  static const String messagesCollection = 'messages';
  static const String contactsCollection = 'emergency_contacts';
  static const String trustedDevicesCollection = 'trusted_devices';
  static const String loginHistoryCollection = 'login_history';
  static const String knowledgeBaseCollection = 'knowledge_base';
  static const String alertsCollection = 'alerts';
  static const String verificationsCollection = 'verifications';
  static const String scheduledEscalationsCollection = 'scheduled_escalations';

  // ── Firebase Storage path prefixes ─────────────────────────────────────────
  static const String profileImagesPath = 'profile_images';
  static const String reportImagesPath = 'report_images';
}
