-- Backfill alerts.target_state from target_lga.
--
-- 20260927050000 added alerts.target_state, but alerts created before it have
-- the column null, which the app and the push handler read as "legacy: match
-- target_lga by name in any state". Most LGA names occur in exactly one state,
-- so for those the state is recoverable and the alert can be pinned to it.
--
-- The mapping below is the LGA -> state table of
-- lib/core/data/nigeria_locations_data.dart (all 36 states + FCT; the three
-- covered states Benue, Nasarawa and Plateau agree with
-- lib/core/data/mvp_locations_data.dart). Only names that occur in exactly one
-- state are listed, matched case-insensitively against a trimmed target_lga.
--
-- Left alone here (the same name is an LGA of two states, so target_lga cannot
-- say which one is meant): Bassa, Ifelodun, Irepodun, Nasarawa, Obi, Surulere.
-- This migration leaves those alerts with target_state null; the very next
-- migration, 20260927080000, finishes the job — it makes the state mandatory
-- and moves any alert whose target still cannot be resolved to one place into
-- public.alerts_unresolved_target, naming each one in a WARNING, so nothing is
-- left silently matching an LGA name in every state and no admin has to hunt
-- for them.
--
-- 'All' is not an LGA name and is not in the table, so alerts targeting
-- everyone stay untouched (null state + 'All' = every state, as before).
--
-- Safety: alerts only queue a notification_outbox row from the AFTER INSERT
-- trigger alerts_after_insert, so this UPDATE sends no push. The two BEFORE
-- UPDATE triggers are alerts_touch (bumps updated_at) and alerts_guard_author
-- (rejects a change of created_by, which this does not touch).

with lga_state (lga, state) as (
  values
    ('aba north', 'Abia'),
    ('aba south', 'Abia'),
    ('abadam', 'Borno'),
    ('abaji', 'FCT'),
    ('abak', 'Akwa Ibom'),
    ('abakaliki', 'Ebonyi'),
    ('abeokuta north', 'Ogun'),
    ('abeokuta south', 'Ogun'),
    ('abi', 'Cross River'),
    ('aboh mbaise', 'Imo'),
    ('abua/odual', 'Rivers'),
    ('adavi', 'Kogi'),
    ('ado', 'Benue'),
    ('ado ekiti', 'Ekiti'),
    ('ado-odo/ota', 'Ogun'),
    ('afijio', 'Oyo'),
    ('afikpo north', 'Ebonyi'),
    ('afikpo south', 'Ebonyi'),
    ('agaie', 'Niger'),
    ('agatu', 'Benue'),
    ('agege', 'Lagos'),
    ('aguata', 'Anambra'),
    ('agwara', 'Niger'),
    ('ahiazu mbaise', 'Imo'),
    ('ahoada east', 'Rivers'),
    ('ahoada west', 'Rivers'),
    ('aiyedaade', 'Osun'),
    ('aiyedire', 'Osun'),
    ('ajaokuta', 'Kogi'),
    ('ajeromi-ifelodun', 'Lagos'),
    ('ajingi', 'Kano'),
    ('akamkpa', 'Cross River'),
    ('akinyele', 'Oyo'),
    ('akko', 'Gombe'),
    ('akoko north-east', 'Ondo'),
    ('akoko north-west', 'Ondo'),
    ('akoko south-east', 'Ondo'),
    ('akoko south-west', 'Ondo'),
    ('akoko-edo', 'Edo'),
    ('akpabuyo', 'Cross River'),
    ('akuku-toru', 'Rivers'),
    ('akure north', 'Ondo'),
    ('akure south', 'Ondo'),
    ('akwanga', 'Nasarawa'),
    ('albasu', 'Kano'),
    ('aleiro', 'Kebbi'),
    ('alimosho', 'Lagos'),
    ('alkaleri', 'Bauchi'),
    ('amuwo-odofin', 'Lagos'),
    ('anambra east', 'Anambra'),
    ('anambra west', 'Anambra'),
    ('anaocha', 'Anambra'),
    ('andoni', 'Rivers'),
    ('aninri', 'Enugu'),
    ('aniocha north', 'Delta'),
    ('aniocha south', 'Delta'),
    ('anka', 'Zamfara'),
    ('ankpa', 'Kogi'),
    ('apa', 'Benue'),
    ('apapa', 'Lagos'),
    ('ardo kola', 'Taraba'),
    ('arewa dandi', 'Kebbi'),
    ('argungu', 'Kebbi'),
    ('arochukwu', 'Abia'),
    ('asa', 'Kwara'),
    ('asari-toru', 'Rivers'),
    ('askira/uba', 'Borno'),
    ('atakunmosa east', 'Osun'),
    ('atakunmosa west', 'Osun'),
    ('atiba', 'Oyo'),
    ('atisbo', 'Oyo'),
    ('augie', 'Kebbi'),
    ('auyo', 'Jigawa'),
    ('awe', 'Nasarawa'),
    ('awgu', 'Enugu'),
    ('awka north', 'Anambra'),
    ('awka south', 'Anambra'),
    ('ayamelum', 'Anambra'),
    ('babura', 'Jigawa'),
    ('badagry', 'Lagos'),
    ('bade', 'Yobe'),
    ('bagudo', 'Kebbi'),
    ('bagwai', 'Kano'),
    ('bakassi', 'Cross River'),
    ('bakori', 'Katsina'),
    ('bakura', 'Zamfara'),
    ('balanga', 'Gombe'),
    ('bali', 'Taraba'),
    ('bama', 'Borno'),
    ('barkin ladi', 'Plateau'),
    ('baruten', 'Kwara'),
    ('batagarawa', 'Katsina'),
    ('batsari', 'Katsina'),
    ('bauchi', 'Bauchi'),
    ('baure', 'Katsina'),
    ('bayo', 'Borno'),
    ('bebeji', 'Kano'),
    ('bekwarra', 'Cross River'),
    ('bende', 'Abia'),
    ('biase', 'Cross River'),
    ('bichi', 'Kano'),
    ('bida', 'Niger'),
    ('billiri', 'Gombe'),
    ('bindawa', 'Katsina'),
    ('binji', 'Sokoto'),
    ('biriniwa', 'Jigawa'),
    ('birnin gwari', 'Kaduna'),
    ('birnin kebbi', 'Kebbi'),
    ('birnin kudu', 'Jigawa'),
    ('birnin magaji/kiyaw', 'Zamfara'),
    ('biu', 'Borno'),
    ('bodinga', 'Sokoto'),
    ('bogoro', 'Bauchi'),
    ('boki', 'Cross River'),
    ('bokkos', 'Plateau'),
    ('boluwaduro', 'Osun'),
    ('bomadi', 'Delta'),
    ('bonny', 'Rivers'),
    ('borgu', 'Niger'),
    ('boripe', 'Osun'),
    ('bosso', 'Niger'),
    ('brass', 'Bayelsa'),
    ('buji', 'Jigawa'),
    ('bukkuyum', 'Zamfara'),
    ('bungudu', 'Zamfara'),
    ('bunkure', 'Kano'),
    ('bunza', 'Kebbi'),
    ('bursari', 'Yobe'),
    ('buruku', 'Benue'),
    ('burutu', 'Delta'),
    ('bwari', 'FCT'),
    ('calabar municipal', 'Cross River'),
    ('calabar south', 'Cross River'),
    ('chafe', 'Zamfara'),
    ('chanchaga', 'Niger'),
    ('charanchi', 'Katsina'),
    ('chibok', 'Borno'),
    ('chikun', 'Kaduna'),
    ('dala', 'Kano'),
    ('damaturu', 'Yobe'),
    ('damban', 'Bauchi'),
    ('dambatta', 'Kano'),
    ('damboa', 'Borno'),
    ('dan musa', 'Katsina'),
    ('dandi', 'Kebbi'),
    ('dandume', 'Katsina'),
    ('dange shuni', 'Sokoto'),
    ('danja', 'Katsina'),
    ('darazo', 'Bauchi'),
    ('dass', 'Bauchi'),
    ('daura', 'Katsina'),
    ('dawakin kudu', 'Kano'),
    ('dawakin tofa', 'Kano'),
    ('degema', 'Rivers'),
    ('dekina', 'Kogi'),
    ('demsa', 'Adamawa'),
    ('dikwa', 'Borno'),
    ('doguwa', 'Kano'),
    ('doma', 'Nasarawa'),
    ('donga', 'Taraba'),
    ('dukku', 'Gombe'),
    ('dunukofia', 'Anambra'),
    ('dutse', 'Jigawa'),
    ('dutsi', 'Katsina'),
    ('dutsin ma', 'Katsina'),
    ('eastern obolo', 'Akwa Ibom'),
    ('ebonyi', 'Ebonyi'),
    ('edati', 'Niger'),
    ('ede north', 'Osun'),
    ('ede south', 'Osun'),
    ('edu', 'Kwara'),
    ('efe', 'Osun'),
    ('efon', 'Ekiti'),
    ('egbado north', 'Ogun'),
    ('egbado south', 'Ogun'),
    ('egbeda', 'Oyo'),
    ('egor', 'Edo'),
    ('ehime mbano', 'Imo'),
    ('ejigbo', 'Osun'),
    ('ekeremor', 'Bayelsa'),
    ('eket', 'Akwa Ibom'),
    ('ekiti', 'Kwara'),
    ('ekiti east', 'Ekiti'),
    ('ekiti south-west', 'Ekiti'),
    ('ekiti west', 'Ekiti'),
    ('ekwusigo', 'Anambra'),
    ('eleme', 'Rivers'),
    ('emohua', 'Rivers'),
    ('emure', 'Ekiti'),
    ('enugu east', 'Enugu'),
    ('enugu north', 'Enugu'),
    ('enugu south', 'Enugu'),
    ('epe', 'Lagos'),
    ('esan central', 'Edo'),
    ('esan north-east', 'Edo'),
    ('esan south-east', 'Edo'),
    ('esan west', 'Edo'),
    ('ese odo', 'Ondo'),
    ('esit eket', 'Akwa Ibom'),
    ('essien udim', 'Akwa Ibom'),
    ('etche', 'Rivers'),
    ('ethiope east', 'Delta'),
    ('ethiope west', 'Delta'),
    ('eti osa', 'Lagos'),
    ('etim ekpo', 'Akwa Ibom'),
    ('etinan', 'Akwa Ibom'),
    ('etsako central', 'Edo'),
    ('etsako east', 'Edo'),
    ('etsako west', 'Edo'),
    ('etung', 'Cross River'),
    ('ewekoro', 'Ogun'),
    ('ezeagu', 'Enugu'),
    ('ezinihitte', 'Imo'),
    ('ezza north', 'Ebonyi'),
    ('ezza south', 'Ebonyi'),
    ('fagge', 'Kano'),
    ('fakai', 'Kebbi'),
    ('faskari', 'Katsina'),
    ('fika', 'Yobe'),
    ('fufure', 'Adamawa'),
    ('funakaye', 'Gombe'),
    ('fune', 'Yobe'),
    ('funtua', 'Katsina'),
    ('gabasawa', 'Kano'),
    ('gada', 'Sokoto'),
    ('gagarawa', 'Jigawa'),
    ('gamawa', 'Bauchi'),
    ('ganjuwa', 'Bauchi'),
    ('ganye', 'Adamawa'),
    ('garki', 'Jigawa'),
    ('garko', 'Kano'),
    ('garun mallam', 'Kano'),
    ('gashaka', 'Taraba'),
    ('gassol', 'Taraba'),
    ('gaya', 'Kano'),
    ('gayuk', 'Adamawa'),
    ('gbako', 'Niger'),
    ('gboko', 'Benue'),
    ('gbonyin', 'Ekiti'),
    ('geidam', 'Yobe'),
    ('gezawa', 'Kano'),
    ('giade', 'Bauchi'),
    ('giwa', 'Kaduna'),
    ('gokana', 'Rivers'),
    ('gombe', 'Gombe'),
    ('gombi', 'Adamawa'),
    ('goronyo', 'Sokoto'),
    ('grie', 'Adamawa'),
    ('gubio', 'Borno'),
    ('gudu', 'Sokoto'),
    ('gujba', 'Yobe'),
    ('gulani', 'Yobe'),
    ('guma', 'Benue'),
    ('gumel', 'Jigawa'),
    ('gummi', 'Zamfara'),
    ('gurara', 'Niger'),
    ('guri', 'Jigawa'),
    ('gusau', 'Zamfara'),
    ('guzamala', 'Borno'),
    ('gwadabawa', 'Sokoto'),
    ('gwagwalada', 'FCT'),
    ('gwale', 'Kano'),
    ('gwandu', 'Kebbi'),
    ('gwaram', 'Jigawa'),
    ('gwarzo', 'Kano'),
    ('gwer east', 'Benue'),
    ('gwer west', 'Benue'),
    ('gwiwa', 'Jigawa'),
    ('gwoza', 'Borno'),
    ('hadejia', 'Jigawa'),
    ('hawul', 'Borno'),
    ('hong', 'Adamawa'),
    ('ibadan north', 'Oyo'),
    ('ibadan north-east', 'Oyo'),
    ('ibadan north-west', 'Oyo'),
    ('ibadan south-east', 'Oyo'),
    ('ibadan south-west', 'Oyo'),
    ('ibaji', 'Kogi'),
    ('ibarapa central', 'Oyo'),
    ('ibarapa east', 'Oyo'),
    ('ibarapa north', 'Oyo'),
    ('ibeju-lekki', 'Lagos'),
    ('ibeno', 'Akwa Ibom'),
    ('ibesikpo asutan', 'Akwa Ibom'),
    ('ibi', 'Taraba'),
    ('ibiono-ibom', 'Akwa Ibom'),
    ('idah', 'Kogi'),
    ('idanre', 'Ondo'),
    ('ideato north', 'Imo'),
    ('ideato south', 'Imo'),
    ('idemili north', 'Anambra'),
    ('idemili south', 'Anambra'),
    ('ido', 'Oyo'),
    ('ido osi', 'Ekiti'),
    ('ifako-ijaiye', 'Lagos'),
    ('ifedayo', 'Osun'),
    ('ifedore', 'Ondo'),
    ('ifo', 'Ogun'),
    ('igabi', 'Kaduna'),
    ('igalamela odolu', 'Kogi'),
    ('igbo etiti', 'Enugu'),
    ('igbo eze north', 'Enugu'),
    ('igbo eze south', 'Enugu'),
    ('igueben', 'Edo'),
    ('ihiala', 'Anambra'),
    ('ihitte/uboma', 'Imo'),
    ('ijebu east', 'Ogun'),
    ('ijebu north', 'Ogun'),
    ('ijebu north east', 'Ogun'),
    ('ijebu ode', 'Ogun'),
    ('ijero', 'Ekiti'),
    ('ijumu', 'Kogi'),
    ('ika', 'Akwa Ibom'),
    ('ika north east', 'Delta'),
    ('ika south', 'Delta'),
    ('ikara', 'Kaduna'),
    ('ikeduru', 'Imo'),
    ('ikeja', 'Lagos'),
    ('ikenne', 'Ogun'),
    ('ikere', 'Ekiti'),
    ('ikole', 'Ekiti'),
    ('ikom', 'Cross River'),
    ('ikono', 'Akwa Ibom'),
    ('ikorodu', 'Lagos'),
    ('ikot abasi', 'Akwa Ibom'),
    ('ikot ekpene', 'Akwa Ibom'),
    ('ikpoba okha', 'Edo'),
    ('ikwerre', 'Rivers'),
    ('ikwo', 'Ebonyi'),
    ('ikwuano', 'Abia'),
    ('ila', 'Osun'),
    ('ilaje', 'Ondo'),
    ('ile oluji/okeigbo', 'Ondo'),
    ('ilejemeje', 'Ekiti'),
    ('ilesa east', 'Osun'),
    ('ilesa west', 'Osun'),
    ('illela', 'Sokoto'),
    ('ilorin east', 'Kwara'),
    ('ilorin south', 'Kwara'),
    ('ilorin west', 'Kwara'),
    ('imeko afon', 'Ogun'),
    ('ingawa', 'Katsina'),
    ('ini', 'Akwa Ibom'),
    ('ipokia', 'Ogun'),
    ('irele', 'Ondo'),
    ('irepo', 'Oyo'),
    ('irepodun/ifelodun', 'Ekiti'),
    ('irewole', 'Osun'),
    ('isa', 'Sokoto'),
    ('ise/orun', 'Ekiti'),
    ('iseyin', 'Oyo'),
    ('ishielu', 'Ebonyi'),
    ('isi uzo', 'Enugu'),
    ('isiala mbano', 'Imo'),
    ('isiala ngwa north', 'Abia'),
    ('isiala ngwa south', 'Abia'),
    ('isin', 'Kwara'),
    ('isokan', 'Osun'),
    ('isoko north', 'Delta'),
    ('isoko south', 'Delta'),
    ('isu', 'Imo'),
    ('isuikwuato', 'Abia'),
    ('itas/gadau', 'Bauchi'),
    ('itesiwaju', 'Oyo'),
    ('itu', 'Akwa Ibom'),
    ('ivo', 'Ebonyi'),
    ('iwajowa', 'Oyo'),
    ('iwo', 'Osun'),
    ('izzi', 'Ebonyi'),
    ('jaba', 'Kaduna'),
    ('jada', 'Adamawa'),
    ('jahun', 'Jigawa'),
    ('jakusko', 'Yobe'),
    ('jalingo', 'Taraba'),
    ('jama''are', 'Bauchi'),
    ('jega', 'Kebbi'),
    ('jema''a', 'Kaduna'),
    ('jere', 'Borno'),
    ('jibia', 'Katsina'),
    ('jos east', 'Plateau'),
    ('jos north', 'Plateau'),
    ('jos south', 'Plateau'),
    ('kabba/bunu', 'Kogi'),
    ('kabo', 'Kano'),
    ('kachia', 'Kaduna'),
    ('kaduna north', 'Kaduna'),
    ('kaduna south', 'Kaduna'),
    ('kafin hausa', 'Jigawa'),
    ('kafur', 'Katsina'),
    ('kaga', 'Borno'),
    ('kagarko', 'Kaduna'),
    ('kaiama', 'Kwara'),
    ('kaita', 'Katsina'),
    ('kajola', 'Oyo'),
    ('kajuru', 'Kaduna'),
    ('kala/balge', 'Borno'),
    ('kalgo', 'Kebbi'),
    ('kaltungo', 'Gombe'),
    ('kanam', 'Plateau'),
    ('kankara', 'Katsina'),
    ('kanke', 'Plateau'),
    ('kankia', 'Katsina'),
    ('kano municipal', 'Kano'),
    ('karasuwa', 'Yobe'),
    ('karaye', 'Kano'),
    ('karim lamido', 'Taraba'),
    ('karu', 'Nasarawa'),
    ('katagum', 'Bauchi'),
    ('katcha', 'Niger'),
    ('katsina', 'Katsina'),
    ('katsina-ala', 'Benue'),
    ('kaugama', 'Jigawa'),
    ('kaura', 'Kaduna'),
    ('kaura namoda', 'Zamfara'),
    ('kauru', 'Kaduna'),
    ('kazaure', 'Jigawa'),
    ('keana', 'Nasarawa'),
    ('kebbe', 'Sokoto'),
    ('keffi', 'Nasarawa'),
    ('khana', 'Rivers'),
    ('kibiya', 'Kano'),
    ('kirfi', 'Bauchi'),
    ('kiri kasama', 'Jigawa'),
    ('kiru', 'Kano'),
    ('kiyawa', 'Jigawa'),
    ('kogi', 'Kogi'),
    ('koko/besse', 'Kebbi'),
    ('kokona', 'Nasarawa'),
    ('kolokuma/opokuma', 'Bayelsa'),
    ('konduga', 'Borno'),
    ('konshisha', 'Benue'),
    ('kontagora', 'Niger'),
    ('kosofe', 'Lagos'),
    ('kubau', 'Kaduna'),
    ('kudan', 'Kaduna'),
    ('kuje', 'FCT'),
    ('kukawa', 'Borno'),
    ('kumbotso', 'Kano'),
    ('kumi', 'Taraba'),
    ('kunchi', 'Kano'),
    ('kura', 'Kano'),
    ('kurfi', 'Katsina'),
    ('kusada', 'Katsina'),
    ('kwali', 'FCT'),
    ('kwami', 'Gombe'),
    ('kwande', 'Benue'),
    ('kware', 'Sokoto'),
    ('kwaya kusar', 'Borno'),
    ('lafia', 'Nasarawa'),
    ('lagelu', 'Oyo'),
    ('lagos island', 'Lagos'),
    ('lagos mainland', 'Lagos'),
    ('lamurde', 'Adamawa'),
    ('langtang north', 'Plateau'),
    ('langtang south', 'Plateau'),
    ('lapai', 'Niger'),
    ('lau', 'Taraba'),
    ('lavun', 'Niger'),
    ('lere', 'Kaduna'),
    ('logo', 'Benue'),
    ('lokoja', 'Kogi'),
    ('machina', 'Yobe'),
    ('madagali', 'Adamawa'),
    ('madobi', 'Kano'),
    ('mafa', 'Borno'),
    ('magama', 'Niger'),
    ('magumeri', 'Borno'),
    ('mai''adua', 'Katsina'),
    ('maiduguri', 'Borno'),
    ('maigatari', 'Jigawa'),
    ('maiha', 'Adamawa'),
    ('maiyama', 'Kebbi'),
    ('makarfi', 'Kaduna'),
    ('makoda', 'Kano'),
    ('makurdi', 'Benue'),
    ('malam madori', 'Jigawa'),
    ('malumfashi', 'Katsina'),
    ('mangu', 'Plateau'),
    ('mani', 'Katsina'),
    ('maradun', 'Zamfara'),
    ('mariga', 'Niger'),
    ('marte', 'Borno'),
    ('maru', 'Zamfara'),
    ('mashegu', 'Niger'),
    ('mashi', 'Katsina'),
    ('matazu', 'Katsina'),
    ('mayo belwa', 'Adamawa'),
    ('mbaitoli', 'Imo'),
    ('mbo', 'Akwa Ibom'),
    ('michika', 'Adamawa'),
    ('miga', 'Jigawa'),
    ('mikang', 'Plateau'),
    ('minjibir', 'Kano'),
    ('misau', 'Bauchi'),
    ('mkpat-enin', 'Akwa Ibom'),
    ('moba', 'Ekiti'),
    ('mobbar', 'Borno'),
    ('mokwa', 'Niger'),
    ('monguno', 'Borno'),
    ('mopa muro', 'Kogi'),
    ('moro', 'Kwara'),
    ('moya', 'Niger'),
    ('mubi north', 'Adamawa'),
    ('mubi south', 'Adamawa'),
    ('municipal area council', 'FCT'),
    ('musawa', 'Katsina'),
    ('mushin', 'Lagos'),
    ('nafada', 'Gombe'),
    ('nangere', 'Yobe'),
    ('nasarawa egon', 'Nasarawa'),
    ('ndokwa east', 'Delta'),
    ('ndokwa west', 'Delta'),
    ('nembe', 'Bayelsa'),
    ('ngala', 'Borno'),
    ('nganzai', 'Borno'),
    ('ngaski', 'Kebbi'),
    ('ngor okpala', 'Imo'),
    ('nguru', 'Yobe'),
    ('ningi', 'Bauchi'),
    ('njaba', 'Imo'),
    ('njikoka', 'Anambra'),
    ('nkanu east', 'Enugu'),
    ('nkanu west', 'Enugu'),
    ('nkwerre', 'Imo'),
    ('nnewi north', 'Anambra'),
    ('nnewi south', 'Anambra'),
    ('nsit-atai', 'Akwa Ibom'),
    ('nsit-ibom', 'Akwa Ibom'),
    ('nsit-ubium', 'Akwa Ibom'),
    ('nsukka', 'Enugu'),
    ('numan', 'Adamawa'),
    ('nwangele', 'Imo'),
    ('obafemi owode', 'Ogun'),
    ('obanliku', 'Cross River'),
    ('obi ngwa', 'Abia'),
    ('obio/akpor', 'Rivers'),
    ('obokun', 'Osun'),
    ('obot akara', 'Akwa Ibom'),
    ('obowo', 'Imo'),
    ('obubra', 'Cross River'),
    ('obudu', 'Cross River'),
    ('odeda', 'Ogun'),
    ('odigbo', 'Ondo'),
    ('odo otin', 'Osun'),
    ('odogbolu', 'Ogun'),
    ('odukpani', 'Cross River'),
    ('offa', 'Kwara'),
    ('ofu', 'Kogi'),
    ('ogba/egbema/ndoni', 'Rivers'),
    ('ogbadibo', 'Benue'),
    ('ogbaru', 'Anambra'),
    ('ogbia', 'Bayelsa'),
    ('ogbomosho north', 'Oyo'),
    ('ogbomosho south', 'Oyo'),
    ('ogo oluwa', 'Oyo'),
    ('ogoja', 'Cross River'),
    ('ogori/magongo', 'Kogi'),
    ('ogu/bolo', 'Rivers'),
    ('ogun waterside', 'Ogun'),
    ('oguta', 'Imo'),
    ('ohafia', 'Abia'),
    ('ohaji/egbema', 'Imo'),
    ('ohaozara', 'Ebonyi'),
    ('ohaukwu', 'Ebonyi'),
    ('ohimini', 'Benue'),
    ('oji river', 'Enugu'),
    ('ojo', 'Lagos'),
    ('oju', 'Benue'),
    ('oke ero', 'Kwara'),
    ('okehi', 'Kogi'),
    ('okene', 'Kogi'),
    ('okigwe', 'Imo'),
    ('okitipupa', 'Ondo'),
    ('okobo', 'Akwa Ibom'),
    ('okpe', 'Delta'),
    ('okpokwu', 'Benue'),
    ('okrika', 'Rivers'),
    ('ola oluwa', 'Osun'),
    ('olamaboro', 'Kogi'),
    ('olorunda', 'Osun'),
    ('olorunsogo', 'Oyo'),
    ('oluyole', 'Oyo'),
    ('omala', 'Kogi'),
    ('omuma', 'Rivers'),
    ('ona ara', 'Oyo'),
    ('ondo east', 'Ondo'),
    ('ondo west', 'Ondo'),
    ('onicha', 'Ebonyi'),
    ('onitsha north', 'Anambra'),
    ('onitsha south', 'Anambra'),
    ('onna', 'Akwa Ibom'),
    ('opobo/nkoro', 'Rivers'),
    ('oredo', 'Edo'),
    ('orelope', 'Oyo'),
    ('orhionmwon', 'Edo'),
    ('ori ire', 'Oyo'),
    ('oriade', 'Osun'),
    ('orlu', 'Imo'),
    ('orolu', 'Osun'),
    ('oron', 'Akwa Ibom'),
    ('orsu', 'Imo'),
    ('oru east', 'Imo'),
    ('oru west', 'Imo'),
    ('oruk anam', 'Akwa Ibom'),
    ('orumba north', 'Anambra'),
    ('orumba south', 'Anambra'),
    ('ose', 'Ondo'),
    ('oshimili north', 'Delta'),
    ('oshimili south', 'Delta'),
    ('oshodi-isolo', 'Lagos'),
    ('osisioma', 'Abia'),
    ('osogbo', 'Osun'),
    ('oturkpo', 'Benue'),
    ('ovia north-east', 'Edo'),
    ('ovia south-west', 'Edo'),
    ('owan east', 'Edo'),
    ('owan west', 'Edo'),
    ('owerri municipal', 'Imo'),
    ('owerri north', 'Imo'),
    ('owerri west', 'Imo'),
    ('owo', 'Ondo'),
    ('oye', 'Ekiti'),
    ('oyi', 'Anambra'),
    ('oyigbo', 'Rivers'),
    ('oyo east', 'Oyo'),
    ('oyo west', 'Oyo'),
    ('oyun', 'Kwara'),
    ('paikoro', 'Niger'),
    ('pankshin', 'Plateau'),
    ('patani', 'Delta'),
    ('pategi', 'Kwara'),
    ('port harcourt', 'Rivers'),
    ('potiskum', 'Yobe'),
    ('qua''an pan', 'Plateau'),
    ('rabah', 'Sokoto'),
    ('rafi', 'Niger'),
    ('rano', 'Kano'),
    ('remo north', 'Ogun'),
    ('rijau', 'Niger'),
    ('rimi', 'Katsina'),
    ('rimin gado', 'Kano'),
    ('ringim', 'Jigawa'),
    ('riyom', 'Plateau'),
    ('rogo', 'Kano'),
    ('roni', 'Jigawa'),
    ('sabon birni', 'Sokoto'),
    ('sabon gari', 'Kaduna'),
    ('sabuwa', 'Katsina'),
    ('safana', 'Katsina'),
    ('sagbama', 'Bayelsa'),
    ('sakaba', 'Kebbi'),
    ('saki east', 'Oyo'),
    ('saki west', 'Oyo'),
    ('sandamu', 'Katsina'),
    ('sanga', 'Kaduna'),
    ('sapele', 'Delta'),
    ('sardauna', 'Taraba'),
    ('shagamu', 'Ogun'),
    ('shagari', 'Sokoto'),
    ('shanga', 'Kebbi'),
    ('shani', 'Borno'),
    ('shanono', 'Kano'),
    ('shelleng', 'Adamawa'),
    ('shendam', 'Plateau'),
    ('shinkafi', 'Zamfara'),
    ('shira', 'Bauchi'),
    ('shiroro', 'Niger'),
    ('shomolu', 'Lagos'),
    ('shongom', 'Gombe'),
    ('silame', 'Sokoto'),
    ('soba', 'Kaduna'),
    ('sokoto north', 'Sokoto'),
    ('sokoto south', 'Sokoto'),
    ('song', 'Adamawa'),
    ('southern ijaw', 'Bayelsa'),
    ('sule tankarkar', 'Jigawa'),
    ('suleja', 'Niger'),
    ('sumaila', 'Kano'),
    ('suru', 'Kebbi'),
    ('tafa', 'Niger'),
    ('tafawa balewa', 'Bauchi'),
    ('tai', 'Rivers'),
    ('takai', 'Kano'),
    ('takum', 'Taraba'),
    ('talata mafara', 'Zamfara'),
    ('tambuwal', 'Sokoto'),
    ('tangaza', 'Sokoto'),
    ('tarauni', 'Kano'),
    ('tarka', 'Benue'),
    ('tarmuwa', 'Yobe'),
    ('taura', 'Jigawa'),
    ('tofa', 'Kano'),
    ('toro', 'Bauchi'),
    ('toto', 'Nasarawa'),
    ('toungo', 'Adamawa'),
    ('tsanyawa', 'Kano'),
    ('tudun wada', 'Kano'),
    ('tureta', 'Sokoto'),
    ('udenu', 'Enugu'),
    ('udi', 'Enugu'),
    ('udu', 'Delta'),
    ('udung-uko', 'Akwa Ibom'),
    ('ughelli north', 'Delta'),
    ('ughelli south', 'Delta'),
    ('ugwunagbo', 'Abia'),
    ('uhunmwonde', 'Edo'),
    ('ukanafun', 'Akwa Ibom'),
    ('ukum', 'Benue'),
    ('ukwa east', 'Abia'),
    ('ukwa west', 'Abia'),
    ('ukwuani', 'Delta'),
    ('umu nneochi', 'Abia'),
    ('umuahia north', 'Abia'),
    ('umuahia south', 'Abia'),
    ('ungogo', 'Kano'),
    ('unuimo', 'Imo'),
    ('uruan', 'Akwa Ibom'),
    ('urue-offong/oruko', 'Akwa Ibom'),
    ('ushongo', 'Benue'),
    ('ussa', 'Taraba'),
    ('uvwie', 'Delta'),
    ('uyo', 'Akwa Ibom'),
    ('uzo uwani', 'Enugu'),
    ('vandeikya', 'Benue'),
    ('wamako', 'Sokoto'),
    ('wamba', 'Nasarawa'),
    ('warawa', 'Kano'),
    ('warji', 'Bauchi'),
    ('warri north', 'Delta'),
    ('warri south', 'Delta'),
    ('warri south west', 'Delta'),
    ('wasagu/danko', 'Kebbi'),
    ('wase', 'Plateau'),
    ('wudil', 'Kano'),
    ('wukari', 'Taraba'),
    ('wurno', 'Sokoto'),
    ('wushishi', 'Niger'),
    ('yabo', 'Sokoto'),
    ('yagba east', 'Kogi'),
    ('yagba west', 'Kogi'),
    ('yakuur', 'Cross River'),
    ('yala', 'Cross River'),
    ('yamaltu/deba', 'Gombe'),
    ('yankwashi', 'Jigawa'),
    ('yauri', 'Kebbi'),
    ('yenagoa', 'Bayelsa'),
    ('yola north', 'Adamawa'),
    ('yola south', 'Adamawa'),
    ('yorro', 'Taraba'),
    ('yunusari', 'Yobe'),
    ('yusufari', 'Yobe'),
    ('zaki', 'Bauchi'),
    ('zango', 'Katsina'),
    ('zangon kataf', 'Kaduna'),
    ('zaria', 'Kaduna'),
    ('zing', 'Taraba'),
    ('zurmi', 'Zamfara'),
    ('zuru', 'Kebbi')
),
unambiguous as (
  select lga, min(state) as state
  from lga_state
  group by lga
  having count(distinct state) = 1
)
update public.alerts a
   set target_state = u.state
  from unambiguous u
 where a.target_state is null
   and a.target_lga is not null
   and lower(btrim(a.target_lga)) = u.lga;
